### ISSUE TITLE
[Suggestion] Give macro for auto converting all eligible spells to ASE

### ISSUE THREAD

**Issue by emirkmo** [Vauryx/AdvancedSpellEffects#46]
A macro for converting all eligible spells to ASE, and optionally adding them to a new ASE compendium, would be great. Ideally, all SRD ASE spells are also saved to this compendium, or to their own SRD ASE compendium.

**Comment by Vauryx** [comment]
Heya - Sory the Wiki does need to be updated a little bit. Since spell effects are no longer necessarily tied to the name, technically any spell can be made an ASE spell by converting. Thus I can't really "Auto-convert" eligible spells. I could provide a macro to put converted spells inside a macro though, will look at adding that in a future update
