### ISSUE TITLE
Suggestion: Silence Spell

### ISSUE THREAD

**Issue by adriangaro** [Vauryx/AdvancedSpellEffects#5]
Considering there are already some spells which act in a similar matter (have an effect on the map), a good idea for a spell would be Silence. Maybe applying the convenient effect (or a active effect) with the same name when entering the area and leaving the area adds/removes the effect?

Also would it be possible to make the spells more generic, in the sense that we could have an area of effect spell which does something when entering and leaving the template (if possible to check)? You could pass in the options the callback for entering and leaving and passing the token to the callbacks. This would allow to certainly allow more complex behaviour and not require to have a specific implementation of handling effects (convenient effect/cub/dae), applying damage (starting midi qol workflows) implemented in the module and allow the macro writers to probably do that.

**Comment by Vauryx** [comment]
Thanks for the suggestions! Will look into getting sleep added.
As for the second point, that is pretty unlikely, sorry. The backend isn't really built in a way to allow that as the intention with this module was always to provide very easy to use pre-set up macros essentially that a user can call without any programming ability. 
Macro writers already have Wasp's Sequencer module which will let them do that with way more control than I could add into ASE, without making it any more complex. (Arguably less complex since Sequencer is so well documented). Anything less than that is also handled really well by Otigon's Automated Animation's module. At least for the visuals - for playing macros on entering/leaving areas you already have multiple modules like Monk's Active Tiles etc.
