### ISSUE TITLE
Call Lightning Spewing Error Message: Sequencer | Effect | Play - Could not find file...

### ISSUE THREAD

**Issue by Jeznar** [Vauryx/AdvancedSpellEffects#80]
I've been impressed by @Vauryx's AdvancedSpellEffects but bumped into a problem with Call Lightning.  When I activate it and use it, I place the storm cloud (nice effect) and can do lighting strikes.  Unfortunately, I get a seemingly endless stream of error messages that just spam my screen until sometime after I delete everything that was added by the spell:
```
Sequencer | Effect | Play - Could not find file:
jb2a.ui.indicator.red.01.01
```
The problem was my JB2A being out of date.

I'd suggest:

1. Some type of throttle on the error message so it doesn't run out of control.
2. Adding some verbiage (if possible) to suggest the possible cause a bit more clearly.

**Comment by Vauryx** [comment]
The error is being thrown by Sequencer (very correctly) because the asset doesn't exist, there's an error for every instance of the file missing so it is as throttled as it can be. 
There's no way to add a more verbose error for your case as exactly what files are different would depend on the exact version you're on compared to the most recent. 
You should always keep all your modules updated to ensure they work as intended.
